server:
  port: ${port:8001}
spring:
  application:
    name: service-01
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.99.1:8848
        namespace: e1c2fa58-6b69-4802-96cf-f446c37434aa
        group: DMP
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.99.1:8080


# Redis数据库索引（默认为0）
  redis:
    database: 0

    # Redis服务器地址
    host: 192.168.99.1

    # Redis服务器连接端口
    port: 6379

    # Redis服务器连接密码（默认为空）
    password:

    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 200

    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1

    # 连接池中的最大空闲连接
      max-idle: 10

    # 连接池中的最小空闲连接
      min-idle: 0

    # 连接超时时间（毫秒）
    timeout: 1000